import React, { ReactNode } from 'react';

import BlankLayout from 'src/@core/layouts/BlankLayout'

const TermsofUse = () => {
  return (
    <div style={{margin: '20px'}}>
      <div className="d-export-content">
        <h1 id="Chatbook-open-platform-terms-of-service">
          <span>Chatbook Terms of Use</span>
        </h1>
        <p><span>Dear users, welcome to the Chatbook!</span></p>
        
        <p>
          <span>
            Chatbook products and services are jointly owned and operated by ChatbookAi. Before using the Services, please make sure to carefully read and understand this "Chatbook Terms of Use" (hereinafter referred to as "these Terms") as well as other related terms, policies, or guidelines of this platform. When you use a specific function of the Services, there may be separate terms, related business rules, etc. ("Specific Terms") for that specific function. In the event of any conflict between these Terms and the Specific Terms, the provisions of the Specific Terms shall prevail. <strong>All the aforementioned terms and rules form an integral part of these Terms (collectively referred to as "All Terms"), and have the same legal effect as the main text of these Terms.</strong>
          </span>
        </p>
        
        <p>
          <span>
            <strong>
              Among them, the Chatbook Open Platform Terms of Service is specifically applicable to your use of the Application Programming Interface (API) or other developer tools and open platform services provided by this platform.
            </strong>
          </span>
        </p>
        
        <p>
          <span>
            We especially remind you to carefully read (minors under the age of 18 shall read with their legal guardian) and fully understand all the terms before using the Services, especially the terms displayed in bold. When you agree to these Terms through online page clicks, checking boxes, or by actually using our services, it means you and we have reached an agreement on All Terms, you have accepted All Terms and their applicable conditions, and agree to be bound by All Terms. If you disagree with any part of these Terms, or cannot accurately understand our interpretation of any term, please click disagree or stop using our services.
          </span>
        </p>
        

        <h2 id="1services">
          <span>1.</span>
          <strong><span>Services</span></strong>
        </h2>
        
        <p>
          <span>
            1.1 Chatbook's products and services include those provided to you through websites, applications (which may include different versions), software development kits (SDKs) for third-party websites and applications, application programming interfaces (APIs), and innovative forms that emerge with technological development. These encompass platforms with generative artificial intelligence services at their core, among other functionalities (hereinafter referred to as "the Services").
          </span>
        </p>
        
        <p>
          <span>
            1.2 The architecture of the Chatbook model is based on Transformer, and its training framework is PyTorch. Chatbook offers generative artificial intelligence services, where users input text information (hereinafter referred to as "input") into a dialogue box. Based on the user's input, Chatbook produces relevant content as a response (hereinafter referred to as "output" or "generated content"), including text, tables, and code, among others. Chatbook collects and analyzes users' input and output information to enhance recognition and response capabilities, improving the intelligence and content quality of the Services. Users can evaluate the output, including actions such as "like" or "dislike", to provide feedback on their opinion of the information generated by Chatbook.
          </span>
        </p>
        
        <p>
          <span>
            1.3 You can use the Services in web form through terminals such as computers and mobile phones, with specific details subject to those provided by Chatbook. Additionally, Chatbook will continuously enrich the terminals and forms you use for the Services. You understand and agree that Chatbook reserves the right to add new services or change, suspend, or terminate the above services.
          </span>
        </p>
        
        <p>
          <span>
            1.4 Chatbook will take necessary measures (not less than industry practices) to ensure the cyber security and stable operation of the Services. We will also make efforts to enhance and improve technology to ensure a better user experience. If you have any questions or feedback about our services, you can contact us through the method described in Section 12.
          </span>
        </p>
        
        <p>
          <span>
            1.5 We make no warranty that the Services are available or will continue to be available in certain jurisdictions. The functions or features of the Services may also vary in different jurisdictions.
          </span>
        </p>
        

        <h2 id="2account">
          <span>2.</span>
          <strong><span>Account</span></strong>
        </h2>
        
        <p>
          <span>
            2.1 the Services is primarily intended for adults. If you are under 18 years old, please read these Terms with your legal guardian and use the Services only with the consent of your legal guardian. Chatbook fully understands the importance of protecting minors and will take corresponding protective measures in accordance with legal requirements and industry mainstream practices.
          </span>
        </p>
        
        <p>
          <span>
            2.2 Before using the Services, you shall register an account using your Email or Google account as per the page instructions. You must provide accurate, truthful, legal, and valid information as required and confirm your agreement to these Terms, "
          </span>
          <strong><span>Privacy Policy</span></strong>
          <span>
            ," and other related rules and policies. If the materials or information you submit are inaccurate, untrue, non-standard, or if there is a reason for the company to suspect them as incorrect, false, or illegal, we reserve the right to refuse to provide you with related functions. As a result, you may be unable to use this platform and related services or may face restrictions on certain functions during use.{' '}
          </span>
          <strong>
            <span>Your account is your credential for logging in and using the Services. The account is non-transferable, non-giftable, and non-inheritable.</span>
          </strong>
        </p>
        
        <p>
          <span>
            2.3 You understand and undertake that your registered account must not violate relevant laws and regulations. Your account name, avatar, profile, and other registration information and additional account information must not contain illegal or harmful information. You must not open an account in the name of others (including but not limited to impersonating others in a way that can confuse, such as using others' names, titles, trademarks, avatars, etc.). Malicious registration of accounts, including but not limited to frequent or bulk registration of accounts, and submission of inveracious information is not allowed. During account registration and use, you must comply with relevant laws and regulations and must not engage in any behavior that harms national interests, damages the legitimate rights and interests of other citizens, or is detrimental to social morality. We have the right to review the information you submit.
          </span>
        </p>
        
        <p>
          <span>2.4 When you register and use an account, you must commit and guarantee that:</span>
        </p>
        <ul>
          <li>
            <span>You take full responsibility for the authenticity, legality, and validity of the registration information, update the registration information promptly, and must not register an account or use the Services on behalf of others.</span>
          </li>
          <li>
            <span>Safely keep your account and password and take legal responsibility for all activities under that account.</span>
          </li>
          <li>
            <span>Do not maliciously register accounts, including but not limited to frequent or bulk registration.</span>
          </li>
          <li>
            <span>Do not transfer, lend, rent, or provide your account to others in any form.</span>
          </li>
        </ul>
        
        <p>
          <span>
            2.5 If we find that you have engaged in illegal or rule-breaking behavior, such as obtaining account registration through false information, or violating these Terms, we reserve the right to take measures such as demanding correction within a specified period, suspending usage, closing accounts without notice. If users discover any unauthorized use of their accounts, they shall immediately notify us, and we will provide the fullest cooperation and handling.
          </span>
        </p>
        
        <p>
          <span>
            2.6 If you lose your account, forget your password, or leak your verification code, you can follow the procedure to appeal for recovery in a timely manner. We especially reminds you to properly safeguard your account, password, and verification code. After using them, you shall log out securely. You will bear full responsibility for any losses caused by the leakage of your account or password.
          </span>
        </p>
        
        <p>
          <span>
            2.7 Under the agreed conditions, you have the option to discontinue the use of our Services, terminate the contract with us, and delete your account. However, even after the user deletes the account, we still have the right to:
          </span>
        </p>
        <ul>
          <li>
            <span>Retain certain data of the user as required by laws and regulations.</span>
          </li>
          <li>
            <span>Exercise the rights stipulated in these Terms for any illegal or violating behavior committed by the user during the use of the Services before deletion.</span>
          </li>
        </ul>
        

        <h2 id="3requirements-and-restrictions">
          <span>3.</span>
          <strong><span>Requirements and Restrictions</span></strong>
        </h2>
        
        <p>
          <span>
            3.1 You fully understand and agree that, under these Terms, we grant you a revocable, non-transferable, non-exclusive, and non-commercial right to legally use this product and related services. All other rights not expressly authorized by these Terms are reserved by Chatbook, and before exercising such rights, you must obtain written permission from Chatbook. Additionally, Chatbook's failure to exercise any of these rights does not constitute a waiver of those rights. If you publish or disseminate outputs generated by the Services, you must: (1) proactively verify the authenticity and accuracy of the output content to avoid spreading false information; (2) clearly indicate that the output content is generated by artificial intelligence, to alert the public to the synthetic nature of the content; (3) avoid publishing and disseminating any output content that violates the usage specifications of these Terms.
          </span>
        </p>
        
        <p>
          <span>
            3.2 When using the Services provided by Chatbook, users shall comply with these Terms and adhere to the principles of voluntariness, equality, fairness, and good faith. Users shall not use the service to infringe on the legal rights of others or seek unjust benefits, nor shall they disrupt the normal order of the internet platform.
          </span>
        </p>
        
        <p>
          <span>
            3.3 To fulfill legal and compliance requirements, Chatbook has the right to use technical or manual means to review the behavior and information of users using the Services, including but not limited to reviewing inputs and outputs, establishing risk filtering mechanisms, and creating databases for illegal content features.
          </span>
        </p>
        
        <p>
          <span>
            <strong>3.4 You will not use the Services to generate, express or promote content or a chatbot that:</strong>
          </span>
        </p>
        <p>
          <span>(1) is hateful, defamatory, offensive, abusive, tortious or vulgar;</span>
        </p>
        <p>
          <span>(2) is deliberately designed to provoke or antagonize another or is bullying or trolling another;</span>
        </p>
        <p>
          <span>(3) may harass, intimidate, threaten, harm, hurt, scare, distress, embarrass or upset another;</span>
        </p>
        <p>
          <span>(4) is discriminatory such as discriminating another based on race, gender, sexuality, religion, nationality, disability or age;</span>
        </p>
        <p>
          <span>(5) is pornographic, obscene, or sexually explicit (e.g., sexual chatbots);</span>
        </p>
        <p>
          <span>(6) facilitates, promotes, incites or glorifies violence or terrorist/extremism content;</span>
        </p>
        <p>
          <span>(7) exploits, harms, or attempts to exploit or harm or minors or exposes minors to such content; </span>
        </p>
        <p>
          <span>(8) are designed to specifically appeal to or present a persona of any person under the age of 18;</span>
        </p>
        <p>
          <span>(9) constitute, encourage or provide instructions for a criminal offence; or</span>
        </p>
        <p>
          <span>(10) impersonates or is designed to impersonate a celebrity, public figure or a person other than yourself without clearly labelling the content or chatbot as "unofficial" or "parody", unless you have that person's explicit consent.</span>
        </p>
        
        <p>
          <strong><span>3.5 When using our services, you shall comply with the requirements of any applicable laws and regulations, and will not:</span></strong>
        </p>
        <p>
          <span>(1) Engage in illegal activities involving network intrusion, such as: using unauthorized data or accessing unauthorized servers/accounts; forging TCP/IP packet names or partial names; attempting to probe, scan, or test vulnerabilities in the software system or network without permission.</span>
        </p>
        <p>
          <span>(2) Engage in activities that disrupt or damage the normal operation of the network, such as: intentionally generating, spreading malicious programs or viruses; entering public computer networks or other people's computer systems without permission and deleting, modifying, adding stored information, etc.</span>
        </p>
        <p>
          <span>(3) Engage in activities to steal network data, such as: reverse engineering, reverse assembly, reverse compilation, translation, or attempting to discover the source code, models, algorithms, and system source code or underlying components of the software in any way; capturing, copying any content of the Services, including but not limited to using any robots, spiders, or other automatic setups, setting mirrors.</span>
        </p>
        <p>
          <span>(4) Provide programs, tools specifically designed for harmful activities such as network intrusion, disruption of network operation and protective measures, stealing network data, or knowingly supporting others engaged in harmful activities related to network security, by providing technical support, advertising, promotion, payment settlement, etc.</span>
        </p>
        <p>
          <span>(5) Engage in high-risk activities that may cause physical damage, such as military and warfare, development of weapons, explosives or dangerous materials, management or operation of critical infrastructure (such as transportation, energy), creation or distribution of controlled substances or services, etc.</span>
        </p>
        <p>
          <span>(6) Engage in activities that infringe on individual legal rights and harm individual physical and mental health, such as violating the personal rights, property rights, and personal information rights of others.</span>
        </p>
        <p>
          <span>(7) Engage in the infringement of intellectual property rights, trade secrets, and other acts that violate business ethics.</span>
        </p>
        <p>
          <span>(8) Exploit advantages in algorithms, data, platforms, etc., to implement monopolistic and unfair competition practices.</span>
        </p>
        <p>
          <span>(9) Engage in activities that disrupt social order, such as gambling, pornography, drugs, spreading false information, etc.</span>
        </p>
        <p>
          <span>(10) Use the Services for fraudulent, misleading or deceptive activities, including but not limited to passing off or representing chatbot-generated answers as human-generated, plagiarism or academic dishonesty, disinformation, scams or phishing.</span>
        </p>
        <p>
          <span>(11) Developing products and services that compete with the Services using the Services (unless such restriction violates relevant laws and regulations).</span>
        </p>
        <p>
          <span>(12) Removing or tampering with the AI-generated identifiers or prominent identifiers of deep synthesis content related to the Services without the consent of Chatbook or without a legitimate and justifiable basis.</span>
        </p>
        <p>
          <span>(13) Obtaining Outputs in a manner that causes unreasonable load on Chatbook's computer systems or facilities, or engaging in activities that may lead to such situations.</span>
        </p>
        <p>
          <span>(14) Copying, transferring, renting, lending, selling, or providing sublicenses or sublicensing the whole or any part of the service without the authorization of Chatbook.</span>
        </p>
        

        <p>
          <span>3.6 You shall establish organizational and technical measures, including but not limited to user management, data security, monitoring, warning, and emergency disposal, to ensure the integrity, confidentiality, and availability of your systems, networks, information, and data, preventing risks such as data security, public opinion, or misuse and abuse of products or services.</span>
        </p>
        
        
        <h2 id="4intellectual-property">
        <span>4. Intellectual Property</span>
      </h2>
      
      <p>
        <span>
          4.1 Except as provided in the following terms, the intellectual property rights and related interests of the content provided by Chatbook in the Services (including but not limited to software, technology, programs, web pages, text, images, graphics, audio, video, charts, layout design, electronic documents, etc.) belong to Chatbook. The copyright, patent rights, and other intellectual property rights of the software on which Chatbook relies to provide Services are owned by Chatbook, its affiliated entities, or the respective rights holders. Without our permission, no one is allowed to use (including but not limited to monitoring, copying, disseminating, displaying, mirroring, uploading, downloading through any robots, "spiders," or similar programs or devices) the content related services.
        </span>
      </p>
      
      <p>
        <span>
          4.2 You are responsible for all Inputs you submit to our Services and corresponding Outputs. By submitting Inputs to our Services, you represent and warrant that you have all rights, licenses, and permissions that are necessary for us to process the Inputs under our Terms. You also represent and warrant that your submitting Inputs to us and corresponding Outputs will not violate our Terms, or any laws or regulations applicable to those Inputs and Outputs. As between you and Chatbook, and to the extent permitted by applicable law, you retain any right, title, and interest that you have in the Inputs you submit.
        </span>
      </p>
      
      <p>
        <span>
          4.3 By using our Services, you hereby grant us an unconditional, irrevocable, non-exclusive, royalty-free, sublicensable, transferable, perpetual and worldwide licence, to the extent permitted by local law, to reproduce, use, modify your Inputs and Outputs in connection with the provision of the Services.
        </span>
      </p>
      
      <p>
        <span>
          4.4 Without our permission, you or your end users shall not use any trademarks, service marks, trade names, domain names, website names, company logos (LOGOs), URLs, or other prominent brand features related to the Services, including but not limited to "Chatbook," etc., in any way, either singly or in combination. You are not allowed to display, use, or apply for registration of trademarks, domain names, etc., related to the aforementioned terms in any way, and you shall not perform acts that expressly or implicitly indicate the right to display, use, or otherwise deal with these identifiers to others.
        </span>
      </p>
      

      <h2 id="5privacy">
        <span>5. Privacy</span>
      </h2>
      
      <p>
        <span>
          5.1 We respect and protect the personal information and privacy of you and all users of the Services. We collect information that you actively input and provide while using our products and services, as well as information generated by the Services. For detailed rules on how we collect, protect, and use personal information, please carefully read the Privacy Policy.
        </span>
      </p>
      
      <p>
        <span>
          5.2 In order to fulfill the requirements stipulated by laws and regulations or provide the Services specified in these Terms, and under the premise of secure encryption technology processing, strict de-identification rendering, and irreversibility to identify specific individuals, we may, to a minimal extent, use Inputs and Outputs to provide, maintain, operate, develop or improve the Services or the underlying technologies supporting the Services. Please be aware that unless we obtain your separate consent, we will not use the aforementioned data and content for any purposes unrelated to the Services.
        </span>
      </p>
      

      <h2 id="6Complaints and Feedback">
        <span>6. Complaints and Feedback</span>
      </h2>
      
      <p>
        <span>
          If you believe that our service infringes on your intellectual property rights or other rights, or if you find any illegal, false information or behaviors that violate these Terms, or if you have any comments and suggestions about our service, you can submit them by going to the product interface. We take your opinions seriously and will take legal actions accordingly.
        </span>
      </p>
      

      <h2 id="7Exclusion of Warranties">
        <span>7. Exclusion of Warranties</span>
      </h2>
      
      <p>
        <span>
          7.1 NOTHING IN THESE TERMS SHALL AFFECT ANY STATUTORY RIGHTS THAT YOU CANNOT CONTRACTUALLY AGREE TO ALTER OR WAIVE AND ARE LEGALLY ALWAYS ENTITLED TO AS A CONSUMER.
        </span>
      </p>
      
      <p>
        <span>
          7.2 THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND WE MAKE NO WARRANTY, REPRESENTATION OR CONDITION TO YOU WITH RESPECT TO THEM, WHETHER EXPRESSED OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED TERMS AS TO SATISFACTORY QUALITY, FITNESS FOR PURPOSE OR CONFORMANCE WITH DESCRIPTION. IN PARTICULAR, WE DO NOT REPRESENT OR WARRANT TO YOU:
        </span>
      </p>
      <p>
        <span>(1) THAT YOUR USE OF THE SERVICES WILL MEET YOUR REQUIREMENTS;</span>
      </p>
      <p>
        <span>(2) THAT YOUR USE OF THE SERVICES OR ANY PART THEREOF WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR;</span>
      </p>
      <p>
        <span>(3) THAT ANY OUTPUT OR OTHER INFORMATION OBTAINED BY YOU AS A RESULT OF YOUR USE OF THE SERVICES WILL BE ACCURATE, UP-TO-DATE, RELIABLE, NON-INFRINGING OR SECURE;</span>
      </p>
      <p>
        <span>(4) THAT DEFECTS IN THE OPERATION OR FUNCTIONALITY OF THE SERVICES WILL BE CORRECTED; OR</span>
      </p>
      <p>
        <span>(5) WITH RESPECT TO THIRD PARTY OFFERINGS.</span>
      </p>
      
      <p>
        <span>
          7.3 WE MAY CHANGE, SUSPEND, WITHDRAW OR RESTRICT THE AVAILABILITY OF ALL OR ANY PART OF OUR PLATFORM OR SERVICES FOR BUSINESS AND OPERATIONAL REASONS AT ANY TIME WITHOUT NOTICE.
        </span>
      </p>
      
      

      <h2 id="8Indemnification">
        <span>8. Indemnification</span>
      </h2>
      
      <p>
        <span>
          You agree to indemnify, defend, and hold us and our affiliates and licensors (if any) harmless against any liabilities, damages, and costs (including reasonable attorneys' fees) payable to a third party arising out of a breach by you or any user of your account of these Terms, your violation of all applicable laws and regulations or third party rights, your fraud or other illegal acts, or your intentional misconduct or gross negligence, to the extent permitted by the applicable law.
        </span>
      </p>
      

      <h2 id="9Limitation of Liability">
        <span>9. Limitation of Liability</span>
      </h2>
      
      <p>
        <span>
          9.1 When the content provided by the Services includes content from plugins, third-party websites, etc., Chatbook shall not responsible for the effectiveness of this content and do not guarantee the authenticity, legality, or security of any content, products, services, or other materials obtained through these means. You shall carefully evaluate the legality, accuracy, authenticity, applicability, completeness, and security of this content and take prudent preventive measures. If you are unsure about the legality, accuracy, authenticity, practicality, completeness, and security of this content, it is advisable to consult with professionals. To the extent permitted by law, Chatbook is not liable for any personal or property losses incurred by you as a result of using any third-party information or links, including but not limited to losses related to downloading computer viruses, defamation of reputation or goodwill, or infringement of rights such as copyright or intellectual property.
        </span>
      </p>
      
      <p>
        <span>
          9.2 In response to your violation of these Terms or other service terms, Chatbook reserves the right to independently judge and take measures against you, including issuing warnings, setting deadlines for correction, restricting account functions, suspending usage, closing accounts, prohibiting re-registration, deleting relevant content, etc., without the need for prior notification. We have the right to announce the results of the actions taken and, based on the actual circumstances, decide whether to restore usage. For behaviors suspected of violating laws and regulations or involving illegal activities, relevant records will be retained, and reports will be made to the competent authorities in accordance with the law, cooperating with their investigations. You shall be solely responsible for any legal liabilities, claims, demands, or losses asserted by third parties resulting therefrom, and you shall compensate us for any losses incurred, including litigation fees, arbitration fees, attorney fees, notary fees, announcement fees, appraisal fees, travel expenses, investigation and evidence collection fees, compensation, liquidated damages, settlement costs, and administrative fines incurred in protecting our rights.
        </span>
      </p>
      
      <p>
        <span>
          9.3 Unless otherwise agreed, neither party shall bear incidental, consequential, punitive, special, or indirect losses or damages, including but not limited to the loss of profits or goodwill, regardless of how such losses or damages arise or the liability theory they are based on, and irrespective of any litigation brought under breach, tort, compensation, or any other legal grounds, even if informed of the possibility of such losses.
        </span>
      </p>
      

      <h2 id="10Export Control and Sanctions">
        <span>10. Export Control and Sanctions</span>
      </h2>
      
      <p>
        <span>
          You understand that your use of Services, providing Inputs to and obtaining Outputs via Services, might be subject to all applicable laws and regulations of export controls and sanctions laws (collectively "Export Control and Sanctions Laws"). You recognize that you are solely responsible for complying with all applicable Export Control and Sanctions Laws related to the access and use of the Services of you and your end user. You represent and warrant that Services may not be used in or for the benefit of, or exported, re-exported, or transferred (a) to or within any country subject to comprehensive sanctions under Export Control and Sanctions Laws; (b) to any party on any restricted party lists under any applicable Export Control and Sanctions Laws that would prohibit your use of Services. Our Services shall not be used for any end use prohibited by applicable Export Control and Sanctions Laws, and your and your end user's Inputs shall not include material or information that requires a license for release or export.
        </span>
      </p>
      

      <h2 id="11Governing Law and Jurisdiction">
        <span>11. Governing Law and Jurisdiction</span>
      </h2>
      
      <p>
        <span>
          11.1 The establishment, execution, interpretation, and resolution of disputes under these Terms shall be governed by the laws of the People's Republic of China in the mainland.
        </span>
      </p>
      
      <p>
        <span>
          11.2 In the event of a dispute arising from the signing, performance, or interpretation of these Terms, the Parties shall make efforts to resolve it amicably through negotiation. If negotiation fails, either Party has the right to file a lawsuit with a court having jurisdiction over the location of the registered office of Hangzhou Chatbook Artificial Intelligence Co., Ltd.
        </span>
      </p>
      

      <h2 id="12Miscellaneous">
        <span>12. Miscellaneous</span>
      </h2>
      
      <p>
        <span>
          12.1 Your acceptance of these Terms includes acceptance of any modifications Chatbook makes to any term at any time. We have the right to modify these Terms at any time, and the updated Terms will be announced through appropriate channels such as the official website. Once announced, it replaces the original terms. Please refer to the latest version of these Terms on the official website. If you do not accept the modified terms, please stop using the Services immediately. Your continued usage of the Service will be considered as your acceptance of the modified terms.
        </span>
      </p>
      
      <p>
        <span>
          12.2 If you notice any violation of laws and regulations or breach of these Terms or you have any opinions or suggestions regarding these Terms or the Service, you can contact us through the following methods:
        </span>
      </p>
      <p>
        <span>Contact Email: </span>chatbookai@gmail.com
      </p>
    </div>
  </div>
  );
};

TermsofUse.getLayout = (page: ReactNode) => <BlankLayout>{page}</BlankLayout>

export default TermsofUse;
